In [1]:
import numpy as np

In [3]:
np.__version__

'1.15.4'

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# except 0, all other nature number will be regarded as True
np.full((3,3), 0, dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [10]:
a = np.arange(10)
a[a%2!=0]

array([1, 3, 5, 7, 9])

In [11]:
a[a % 2 != 0] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [14]:
bool_indicator = np.full((3,1),0, dtype=bool)
bool_indicator[1] = 1
a = np.zeros((3,3))
b = np.ones((3,1))
np.where(bool_indicator,a,b)

array([[1., 1., 1.],
       [0., 0., 0.],
       [1., 1., 1.]])

In [17]:
#Exercise 6
arr = np.arange(10)
print(np.where(arr % 2 == 1, -1, arr))
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [19]:
#Exercise 7
arr.reshape([2,-1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
#Exercise 8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
a,b,c = np.ogrid[0:5:5j,0:5:5j,0:5:5j]
print(a.shape,a)
print(b.shape,b)
print(c.shape,c)

(5, 1, 1) [[[0.  ]]

 [[1.25]]

 [[2.5 ]]

 [[3.75]]

 [[5.  ]]]
(1, 5, 1) [[[0.  ]
  [1.25]
  [2.5 ]
  [3.75]
  [5.  ]]]
(1, 1, 5) [[[0.   1.25 2.5  3.75 5.  ]]]


In [31]:
a = np.ones((2,2,2))
b = np.zeros((2,2,2))
c = np.hstack((a,b))
print(c, c.shape)

[[[1. 1.]
  [1. 1.]
  [0. 0.]
  [0. 0.]]

 [[1. 1.]
  [1. 1.]
  [0. 0.]
  [0. 0.]]] (2, 4, 2)
